/**
 * Bridges the Apache OpenServerless / OpenWhisk "web action" invocation
 * protocol to SvelteKit's platform-agnostic `Server` (Web standard
 * Request/Response).
 *
 * Web action invocation shape (what OpenServerless calls this action with):
 *   {
 *     __ow_method: 'get' | 'post' | ...,
 *     __ow_headers: { [name]: string },
 *     __ow_path: string,          // path *after* the action name
 *     __ow_query: string,         // raw query string, may be absent
 *     __ow_body: string,          // present for non-GET/HEAD, base64 if binary
 *     ...other action params (bound params / route params)
 *   }
 *
 * Expected return shape:
 *   {
 *     statusCode: number,
 *     headers: { [name]: string },
 *     body: string,               // base64 when `__ow_body` semantics need binary
 *   }
 *
 * See: https://openserverless.apache.org/docs/reference/entities/webactions/
 */

import { Server } from '../server/index.js'; // generated by SvelteKit build, see ../shims.js
import { manifest } from '../server/manifest.js';

/** @type {import('@sveltejs/kit').Server} */
const server = new Server(manifest);
const server_init = server.init({
	env: process.env,
	read: (file) => {
		// Static/prerendered assets are served separately by ops (or a CDN) in
		// production; this hook only matters if you enable SSR asset reads.
		throw new Error(`Cannot read "${file}" from within the OpenServerless action`);
	}
});

const BINARY_CONTENT_TYPE = /^(image|audio|video|font)\/|application\/(octet-stream|pdf|zip|wasm)/i;

/**
 * Rebuilds a Web standard `Request` from the OpenServerless invocation params.
 * @param {Record<string, any>} params
 */
function toRequest(params) {
	const method = (params.__ow_method || 'get').toUpperCase();
	const headers = new Headers(params.__ow_headers || {});

	const host = headers.get('host') || 'localhost';
	const protocol = headers.get('x-forwarded-proto') || 'https';
	const path = params.__ow_path || '/';
	const query = params.__ow_query ? `?${params.__ow_query}` : '';
	const url = `${protocol}://${host}${path}${query}`;

	/** @type {RequestInit} */
	const init = { method, headers };

	if (method !== 'GET' && method !== 'HEAD' && params.__ow_body != null) {
		const isBase64 = params.__ow_isBase64Encoded ?? guessBinary(headers.get('content-type'));
		init.body = isBase64 ? Buffer.from(params.__ow_body, 'base64') : params.__ow_body;
	}

	return new Request(url, init);
}

function guessBinary(contentType) {
	return !!contentType && BINARY_CONTENT_TYPE.test(contentType);
}

/**
 * Converts SvelteKit's Web standard `Response` into the object shape
 * OpenServerless expects a web action to return.
 * @param {Response} response
 */
async function toActivationResult(response) {
	/** @type {Record<string, string>} */
	const headers = {};
	for (const [key, value] of response.headers) {
		headers[key] = value;
	}

	const contentType = response.headers.get('content-type') ?? '';
	const isBinary = guessBinary(contentType);

	let body;
	if (isBinary) {
		const buffer = Buffer.from(await response.arrayBuffer());
		body = buffer.toString('base64');
	} else {
		body = await response.text();
	}

	return {
		statusCode: response.status,
		headers,
		body,
		...(isBinary ? { __ow_isBase64Encoded: true } : {})
	};
}

/**
 * The action's entrypoint. OpenServerless invokes this exported function
 * with the activation params and awaits the returned/resolved object.
 * @param {Record<string, any>} params
 */
export async function main(params) {
	await server_init;

	const request = toRequest(params);

	const response = await server.respond(request, {
		platform: { params },
		getClientAddress: () => params.__ow_headers?.['x-forwarded-for'] ?? '0.0.0.0'
	});

	return toActivationResult(response);
}
